"""add session token_hash

Revision ID: 46e5488156cd
Revises: ecc12c37d3e6
Create Date: 2026-07-28 02:26:50.553239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e5488156cd'
down_revision: Union[str, Sequence[str], None] = 'ecc12c37d3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('token_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'token_hash')
    # ### end Alembic commands ###
